config/routes.rb
Rainbow::Application.routes.draw do
  root 'leprechauns#index'

  resources :treasures

end

app/models/treasure.rb
class Treasure < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leprechauns_controller.rb
class LeprechaunsController < ApplicationController
    def index
    end
end

app/controllers/treasures_controller.rb
class TreasuresController < ApplicationController
    def index
        @treasures = Treasure.all 
    end

    def new
        @treasure = Treasure.new
    end

    def create
        @treasure = Treasure.create(treasure_params)
        redirect_to treasures_path
    end

    private

    def treasure_params
        params.require(:treasure).permit(:item)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leprechauns_helper.rb
module LeprechaunsHelper
end

app/helpers/treasures_helper.rb
module TreasuresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainbow</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width">
</head>
<body>
    <header>
        <div class="col-xs-12 jackpot">
        <h1>Jackpot!! You have found the end of the rainbow.</h1>
        </div>
    </header> 
    <br class="clear" />   

<%= yield %>

</body>
</html>

app/views/leprechauns/index.html.erb
<body>
<div id="treasure_link">
<%= link_to 'Click here to get your treasure', new_treasure_path, :id => 'tlink' %>
</div>
<img src="/assets/lego-leprechaun.jpg" alt="Leprechaun and Pot of Gold">
</body>

app/views/treasures/index.html.erb
<div id="treasure_list">
<h2>Here is our current treasure wishlist.</h2>
<h4>Due to high demand, please anticipate some delay in receipt of your requested item.</h4>
<% @treasures.each do |treasure| %>
    <h3><%= treasure.item %></h3><b />
<% end %>
</div>

app/views/treasures/new.html.erb
<body>
<div class="booyah-box col-xs-10 col-xs-offset-1">
    <h1>Get Your Treasure</h1>
    <p>What would you like to find at the end of the rainbow?</p>
    <%= simple_form_for @treasure do |t| %>
        <%= t.input :item %>
        <br />
        <%= t.submit 'Submit', :class => 'btn btn-primary' %>
    <% end %>
</div>
</body>